### ISSUE TITLE
Shuffle

### ISSUE THREAD

**Issue by xrgouda** [luanpotter/audioplayers#113]
How can i shuffle more than audio and make it play automatic when one finished another one starts (audios in asset folder),, and thank you..

**Comment by luanpotter** [comment]
I think that's beyond the scope of this lib, but you can do the shuffling on your application. Just use the completed event handler to select a new random song from your sample and then call play again with the new song.

Just be sure to be careful with the selected release mode, if not on RELEASE, you are going to need to do that yourself, otherwise memory leaks might occur.

Please let us know if you have more questions!

**Comment by erickzanardo** [comment]
Closing this due this not been inside this lib scope.
