### ISSUE TITLE
replace AudioCache with assetToFile(assertPath, filePath) ?

### ISSUE THREAD

**Issue by devdoomari3** [luanpotter/audioplayers#125]
I looked at AudioCache, and all it does is:
1. make an asset to a file
2. memoize

I think we can refactor AudioCache into:

```
assetToFile( assetPath, filePath)
// and
assetToTempFile (assetPath) 
```

and have users use their own memoize function
(eg. https://docs.flutter.io/flutter/package-async_async/AsyncMemoizer-class.html )

**Comment by erickzanardo** [comment]
@luanpotter what are you thoughts about this?

**Comment by luanpotter** [comment]
@devdoomari3, thanks for the suggestion! :)

But why would we require from the users to do their own memoization? I think AudioCache is a nicely closed package for playing audios from assets because while it might load then in the device, it takes care of not overusing that through its built-in memoization.

It seems to me that you are suggesting that the users of the AudioCache API would need to go to additional steps to use it properly, without any apparent gain (AFAICS). Would you care to elaborate a bit more on the idea and why would it be an improvement?

**Comment by luanpotter** [comment]
Closing as I think this is fine the way it is now.
