### ISSUE TITLE
ios  pod、dealloc

### ISSUE THREAD

**Issue by alenalen** [luanpotter/audioplayers#154]
#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#
Pod::Spec.new do |s|
  s.name             = 'audioplayers'
  s.version          = '0.0.1'
  s.summary          = 'A flutter plugin to play multiple simultaneously audio files.'
  s.description      = <<-DESC
A flutter plugin to play multiple simultaneously audio files.
This is a fork of rxlabz's audioplayer, with the difference that it supports playing multiple audios at the same time, and exposes volume controls.
                       DESC
  s.homepage         = 'https://github.com/luanpotter/audioplayer'
  s.license          = { :file => '../LICENSE.md' }
  s.author           = { 'Luan Nico' => 'luannico27@gmail.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  
  s.ios.deployment_target = '8.0'
end

1、  s.version          = '0.0.1' ??? current 0.11.0  Each pod is 0.0.1；

2、ios , after each play, the dealloc cannot be called

**Comment by alenalen** [comment]
why  user  static NSMutableDictionary * players ?

**Comment by luanpotter** [comment]
1. we update the version of the lib on flutter, not of the android and ios build folders. I believe that's standard for flutter projects, but I might be wrong, what is your take on this? I wouldn't think this would make any difference whatsoever. In fact, that file was generated by flutter...

2. It must, otherwise we are leaking resources. Why do you say it can't be called?

3. Because you can have multiple players. We reference then on the dart side using a String called playerId.

**Comment by erickzanardo** [comment]
Closing due inactivity.
