### ISSUE TITLE
Add an option to visualize audio being played

### ISSUE THREAD

**Issue by dvorapa** [luanpotter/audioplayers#225]

**Comment by erickzanardo** [comment]
What do you mean about visualize audio been played?

**Comment by dvorapa** [comment]
To be able to get the heights of the currently playing audio, something like this:

![66694550_394103817884880_886962500979916800_n](https://user-images.githubusercontent.com/5113916/61127043-68248780-a4ae-11e9-8c9d-bb8da5829855.png)

(in the middle is the current position)

**Comment by luanpotter** [comment]
I think you mean then to get the amplitude of the sound wave in each time? So that you can plot this chart using something else? I'm not sure how easy is to extract that information from the files, it might require complex calculations that might be better suited for a separated library. I'm not an expert either, so maybe someone here can help us out?

**Comment by karnadii** [comment]
try this https://github.com/iamSahdeep/FlutterVisualizers but it need to get audio session id

**Comment by dvorapa** [comment]
> try this https://github.com/iamSahdeep/FlutterVisualizers but it need to get audio session id

This does not support what I want, but its author is willing to add it in the future.

**Comment by dvorapa** [comment]
> I think you mean then to get the amplitude of the sound wave in each time? So that you can plot this chart using something else? I'm not sure how easy is to extract that information from the files, it might require complex calculations that might be better suited for a separated library. I'm not an expert either, so maybe someone here can help us out?

Yeah, I think you are right.

**Comment by erickzanardo** [comment]
@dvorapa does supports https://github.com/iamSahdeep/FlutterVisualizers  what you need? You said that it need an audio session id, is this? https://developer.android.com/reference/android/media/MediaPlayer#getAudioSessionId()

**Comment by dvorapa** [comment]
No, FlutterVisualizers does not support what I need, see https://github.com/iamSahdeep/FlutterVisualizers/issues/1#issuecomment-510914715

**Comment by erickzanardo** [comment]
Okay, if it got implemented, and you need to get the session id, we could see the possibility to implement a getter for that on this package. But since this is a different issue, I will close this. Feel free to open a new one for the audio session id.

**Comment by dvorapa** [comment]
> Okay, if it got implemented, and you need to get the session id, we could see the possibility to implement a getter for that on this package. But since this is a different issue, I will close this. Feel free to open a new one for the audio session id.

Okay, so audioplayers will not support amplitudes and sound waves for songs being played?

**Comment by dvorapa** [comment]
> I'm not sure how easy is to extract that information from the files, it might require complex calculations that might be better suited for a separated library.

Maybe you are right, separate library would do. But it requires someone who knows well internals of native Android audio player and is also more an audio expert

**Comment by erickzanardo** [comment]
I don't think so, this package is focused on playing audio, which already is quite complicated given all the available options, configurations, since this is a visual thing, I guess it out of the scope of this package, and since there is already a lib focused on that, I don't this kind of stuff been implemented here.

But we would gladly implemente a way to fetch the audio session id, so you can use audioplayers alongside a specialized lib for visualizing audio waves.

**Comment by dvorapa** [comment]
This is more like analyzing audio file statically than using current session id.
