### ISSUE TITLE
Very subtle ios versus android bug?

### ISSUE THREAD

**Issue by LarsDu** [luanpotter/audioplayers#236]
I was testing out my hobby app, and I found that if the `isLocal` flag is not explictly set to `true`for audioPlayer.play() for a local file, the file will play just fine on Android, but won't do anything on ios.

The line in question can be demonstrated in my flutter app on ios Simulator iphone 8:
https://github.com/LarsDu/simple_flutter_audio_recorder/blob/master/lib/audio_play_bar.dart

I was testing this on my Android One Plus 6T.

Perhaps this discrepancy could be mentioned in the documentation?

**Comment by luanpotter** [comment]
Yes, that is the case, as expected, because android doesn't require this flag at all. It is capable of figuring it out by itself so the flag is ignored. Only iOS is incapable of that, and thus requires the flag. Of course in order to work on both platforms the flag must be provided, there is no way around it. If you'd like to help out with a PR adding this detail to the docs, please do :)
