### ISSUE TITLE
Audio lag while loop

### ISSUE THREAD

**Issue by praharshbhatt** [luanpotter/audioplayers#246]
This may not be a bug, but while playing an audio file in a loop, there is a delay for around 300ms while the audio file is reset.
our use case defines that there should be no silent instances while playing the file in a loop since the musical note will get horribly mismatched.

Code:
`
    audioCurrentTime = 0;
    audioPlayer.stop();
    audioPlayer.release();
    audioPlayer = await player.loop(fileToPlay+".mp3");
    audioPlayer.setVolume(tanpuraVol);
`

Can this be solved by any chance?
Thanks!

**Comment by erickzanardo** [comment]
Not at the moment, gapless loop are hard to achieve on Android, also mp3 files are even harder to loop without gaps because it has compress information headers.

I have created a specific package for achieving that though, you can check here it here: https://pub.dev/packages/gapless_audio_loop

I is much simpler than audioplayers, but does the job.

**Comment by praharshbhatt** [comment]
Thank you very much
