### ISSUE TITLE
E/AudioAttributes(20124): Invalid stream type -2147483648 for AudioAttributes

### ISSUE THREAD

**Issue by sashkent3** [luanpotter/audioplayers#335]
I keep getting this error, but apart from the message it works properly. Should I bother?

E/AudioAttributes(20124): Invalid stream type -2147483648 for AudioAttributes
W/SoundPool(20124): App requested 100 channels
I/OMXClient(20124): IOmx service obtained
W/AudioTrack(20124): AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 4829
I/OMXClient(20124): IOmx service obtained
W/AudioTrack(20124): AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 4829
I/OMXClient(20124): IOmx service obtained

**Comment by tuarrep** [comment]
I've the same issue.

After investigating the problem occurs when you use `PlayerMode.LOW_LATENCY`:
https://github.com/luanpotter/audioplayers/blob/master/android/src/main/java/xyz/luan/audioplayers/AudioplayersPlugin.java#L157

At line 248 : `AudioManager.USE_DEFAULT_STREAM_TYPE` causes this error because the constant exists but is not is not handled : 
https://github.com/luanpotter/audioplayers/blob/master/android/src/main/java/xyz/luan/audioplayers/WrappedSoundPool.java#L240
https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/media/java/android/media/AudioAttributes.java#882

In my opinion it's just a trick to let Android choose the default stream type: https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/media/java/android/media/AudioManager.java#694

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening

**Comment by masus04** [comment]
Still happening with `audioplayers: ^6.4.0`
