### ISSUE TITLE
Pause playback when app is minimized, and resume when restored.

### ISSUE THREAD

**Issue by emvaized** [luanpotter/audioplayers#382]
Hi, dear community!

I'm using audioplayers package to play background music in my Flutter game.
My issue is that when game is minimized ("home" button was pressed, for example), music keeps playing instead if being paused -- as supposed in my case of usage.

How can I solve this issue? Thanks in advance!

**Comment by luanpotter** [comment]
Hi, @emvaized ! This is intended as audioplayers must be able to work while in the background as well. However, you can pause it yourself if you hold to your reference of `audioplayers` using the `pause` and `resume` methods. In order to do that once app is backgrounded, you can use the `lifecycleStateChange` listener on the game class, just override it to add custom behaviour:

```dart
  @override
  void lifecycleStateChange(AppLifecycleState state) {
    if (state != AppLifecycleState.resumed) {
      pause();
      _ap.pause();
    } else {
      _ap.resume();
    }
  }
```

Here I'm either pausing or resuming the audio since I hold a reference to a hypothetical audioplayers instance and also calling a fictitious pause method on the game that would handle other pause related stuff, like prevent the game from running while backgrounded if that is what you want, or open a in-game pause menu.

Hope this clears it out!

**Comment by emvaized** [comment]
> Hi, @emvaized ! This is intended as audioplayers must be able to work while in the background as well. However, you can pause it yourself if you hold to your reference of `audioplayers` using the `pause` and `resume` methods. In order to do that once app is backgrounded, you can use the `lifecycleStateChange` listener on the game class, just override it to add custom behaviour:
> 
> ```dart
>   @override
>   void lifecycleStateChange(AppLifecycleState state) {
>     if (state != AppLifecycleState.resumed) {
>       pause();
>       _ap.pause();
>     } else {
>       _ap.resume();
>     }
>   }
> ```
> 
> Here I'm either pausing or resuming the audio since I hold a reference to a hypothetical audioplayers instance and also calling a fictitious pause method on the game that would handle other pause related stuff, like prevent the game from running while backgrounded if that is what you want, or open a in-game pause menu.
> 
> Hope this clears it out!

That's exactly how I thought of it! 
I just guessed there may be some built-in method for such a cases.

Anyway, thanks for quick answer! I will move in this direction then.
