### ISSUE TITLE
Please rename GitHub project from audioplayer to audioplayers

### ISSUE THREAD

**Issue by ngocdaothanh** [luanpotter/audioplayers#44]
Google search result shows https://github.com/luanpotter/audioplayer, causing confusion.

Because this project has already been published under the name audioplayers, please also rename the GitHub name to audioplayers.

**Comment by luanpotter** [comment]
Hi @ngocdaothanh ! It is called this way because it was a fork of audioplayer by rxlab, and thus, had to have the same name. Now it can be changed, but I'm not sure that's the best path because people might have already shared and bookmarked the github URL, but I do understand your concern about the confusion it can cause! There is a one phrase disclaimer early in the README addressing that, do you think that is not enough?

**Comment by ngocdaothanh** [comment]
Don't worry about that. GitHub will automatically do the redirection for you.

**Comment by luanpotter** [comment]
Done!
