### ISSUE TITLE
Can't run on REAL iPhone5

### ISSUE THREAD

**Issue by danielhuoo** [luanpotter/audioplayers#446]
My flutter app can run successfully on iPhone6 of iOS 12, and a simulator with iPhone8 of iOS 13. However, I tried to run it on my iPhone5 with Xcode and got the error msg is:

`Non-fat binary /Users/myUserName/Library/Developer/Xcode/DerivedData/Runner-hgzrgeegogvqfyauuvjkxwdvydmk/Build/Products/Debug-iphoneos/Runner.app/Frameworks/audioplayers.framework/audioplayers is not armv7. Running lipo -info:
Non-fat file: /Users/myUserName/Library/Developer/Xcode/DerivedData/Runner-hgzrgeegogvqfyauuvjkxwdvydmk/Build/Products/Debug-iphoneos/Runner.app/Frameworks/audioplayers.framework/audioplayers is architecture: arm64`

I don't understand that if this error caused by my wrong configuration or `audioplayers` is not supported on iPhone5?

**Comment by erickzanardo** [comment]
From a quick research I did, apparently armv7 architecture (which iPhone 5 uses) is dropped on more recently xcode versions, so that is probably why you are seen this error.

I have found this guide that may help you supporting this device version: https://github.com/flutter/flutter/wiki/Supporting-legacy-platforms
