### ISSUE TITLE
Run two files(mp3) one after another without pause

### ISSUE THREAD

**Issue by FetFrumos** [luanpotter/audioplayers#617]
I use your plugin in my app. It's a great job. But I have a question. I need to run two files one after the other, without pause. It must
play cyclically - no pause. is it possible?
Now i play the first file, when the event fires(onPlayerCompletion) I fire the second one - but i have a little pause. I will be grateful for any advice.

**Comment by muarachmann** [comment]
@FetFrumos I believe its default with every music player, It takes time to load the next song into memory and all of that. By **little pause** how long is the wait time probably "seconds". Also it depends if you are loading from local or a remote source and internet connectivity comes into play. So IMO, I think you are doing just well maybe try to do things like load lighter files, and load locally maybe that will suit your use case.

**Comment by erickzanardo** [comment]
This is not possible for two reasons:

 - Audioplayers is more focused on a big feature set than perfomance, so gapless play is not supported
 - Even if this package was perfomance focused, mp3 are compressed format, so there will always be a gap when playing because the player need to uncompress the file before playing, hence the gap.
