### ISSUE TITLE
Please, check the grammar at least before publish a new version

### ISSUE THREAD

**Issue by jinfagang** [luanpotter/audioplayers#739]
previously 0.17.1 got error, then 0.17.2 also got kotlin error.

As a package published pub.dev, it would be better if author take some responsibility for it's correctness, otherwise it will waste a lot of our time.

BTW, does the community have another alternative with audio library? I think this repo is not trustable now.

**Comment by kofan** [comment]
I have not tested it yet, but looks like https://pub.dev/packages/just_audio may be an alternative.

**Comment by luanpotter** [comment]
You got an error because your app was using an outdated version of kotlin, that had nothing wrong with the package. I thoroughly tested all versions before release, and those were no different. Furthermore, since a lot of people failed to do the bare minimum of fixing their own app, I since downgraded the kotlin version so that it would be easier for you to use this plugin.

I try my best to maintain this amongst all my open source packages the best I can, which is a lot of work, in the little free time I have between all my other responsibilities and day job, so it brightens my day when I such a comment. If you don't trust me feel free to leave. Also maybe you should check your own "grammar" on issues you write, since you are requiring this of others I expected yours to be flawless...
