### ISSUE TITLE
setNotification & setNotification

### ISSUE THREAD

**Issue by longfit** [luanpotter/audioplayers#904]
Hi
setNotification & setNotification not defined after upgrade 0.19.0

when I upgraded 0.18.3 to 0.19.0

setNotification & setNotification not define shown 

thanks

**Comment by erickzanardo** [comment]
Please follow the issue template and put more info about it. I am not sure what is the issue here but have you checked our example app [here](https://github.com/luanpotter/audioplayers/tree/master/packages/audioplayers/example)? It has notification and is working with the latest audioplayers version.

**Comment by luanpotter** [comment]
it's just moved to the `notificationService` object inside the audioplayer instance.
